export const cities = [
  { label: "Tarija", id: 1 },
  { label: "Potosí", id: 2 },
  { label: "Sucre", id: 3 },
  { label: "Cochabamba", id: 4 },
  { label: "Santa Cruz", id: 5 },
  { label: "Beni", id: 6 },
  { label: "Pando", id: 7 },
  { label: "Oruro", id: 8 },
  { label: "La Paz", id: 9 },
] as const;

export const categories = [
  "Lubricantes",
  "Filtros",
  "Frenos y Embragues",
  "Motor",
  "Suspensión",
  "Dirección",
  "Transmisión",
  "Sistema Eléctrico",
  "Sistema de Encendido",
  "Sistema de Refrigeración",
  "Correas y Tensores",
  "Rodamientos",
  "Retenes y Empaques",
  "Sensores",
  "Inyección",
  "Escape",
  "Iluminación",
  "Baterías",
  "Accesorios",
  "Herramientas",
  "Limpieza y Cuidado",
  "Aditivos",
  "Líquidos",
  "Neumáticos",
  "Otros",
] as const;